"""nuevo cambio

Revision ID: bb6e011788f9
Revises: 5a8dc04c3d1c
Create Date: 2026-03-27 17:51:50.050318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6e011788f9'
down_revision: Union[str, None] = '5a8dc04c3d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ciudades_id', table_name='ciudades')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ciudades_id', 'ciudades', ['id'], unique=False)
    # ### end Alembic commands ###
