"""initial migration

Revision ID: e2f0b3546361
Revises: 
Create Date: 2026-03-13 16:36:39.227129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f0b3546361'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ciudades', sa.Column('latitud', sa.Float(), nullable=True))
    op.add_column('ciudades', sa.Column('longitud', sa.Float(), nullable=True))
    op.add_column('ciudades', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('ciudades', sa.Column('activa', sa.Boolean(), nullable=True))
    op.alter_column('ciudades', 'pais',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('ciudades_nombre_key', 'ciudades', type_='unique')
    op.create_index(op.f('ix_ciudades_nombre'), 'ciudades', ['nombre'], unique=True)
    op.add_column('metricas_etl', sa.Column('mensaje', sa.String(length=500), nullable=True))
    op.alter_column('metricas_etl', 'ciudades_procesadas',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('metricas_etl', 'registros_insertados',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('metricas_etl', 'errores',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('metricas_etl', 'tiempo_ejecucion',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('metricas_etl', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_metricas_etl_fecha_ejecucion'), 'metricas_etl', ['fecha_ejecucion'], unique=False)
    op.add_column('registros_clima', sa.Column('codigo_tiempo', sa.Integer(), nullable=True))
    op.alter_column('registros_clima', 'ciudad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('registros_clima', 'temperatura',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('registros_clima', 'humedad',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('registros_clima', 'velocidad_viento',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('registros_clima', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index('idx_ciudad_fecha', 'registros_clima', ['ciudad_id', 'fecha_extraccion'], unique=False)
    op.create_index(op.f('ix_registros_clima_ciudad_id'), 'registros_clima', ['ciudad_id'], unique=False)
    op.create_index(op.f('ix_registros_clima_fecha_extraccion'), 'registros_clima', ['fecha_extraccion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_clima_fecha_extraccion'), table_name='registros_clima')
    op.drop_index(op.f('ix_registros_clima_ciudad_id'), table_name='registros_clima')
    op.drop_index('idx_ciudad_fecha', table_name='registros_clima')
    op.alter_column('registros_clima', 'descripcion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('registros_clima', 'velocidad_viento',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('registros_clima', 'humedad',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('registros_clima', 'temperatura',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('registros_clima', 'ciudad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('registros_clima', 'codigo_tiempo')
    op.drop_index(op.f('ix_metricas_etl_fecha_ejecucion'), table_name='metricas_etl')
    op.alter_column('metricas_etl', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('metricas_etl', 'tiempo_ejecucion',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('metricas_etl', 'errores',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('metricas_etl', 'registros_insertados',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('metricas_etl', 'ciudades_procesadas',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('metricas_etl', 'mensaje')
    op.drop_index(op.f('ix_ciudades_nombre'), table_name='ciudades')
    op.create_unique_constraint('ciudades_nombre_key', 'ciudades', ['nombre'])
    op.alter_column('ciudades', 'pais',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('ciudades', 'activa')
    op.drop_column('ciudades', 'fecha_creacion')
    op.drop_column('ciudades', 'longitud')
    op.drop_column('ciudades', 'latitud')
    # ### end Alembic commands ###
