"""crear tablas nasa

Revision ID: a23d2b5760b6
Revises: 
Create Date: 2026-04-10 18:59:23.988698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23d2b5760b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asteroides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nasa_id', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('magnitud_absoluta', sa.Float(), nullable=True),
    sa.Column('diametro_min_km', sa.Float(), nullable=True),
    sa.Column('diametro_max_km', sa.Float(), nullable=True),
    sa.Column('es_peligroso', sa.Boolean(), nullable=True),
    sa.Column('fecha_aproximacion', sa.Date(), nullable=True),
    sa.Column('velocidad_km_s', sa.Float(), nullable=True),
    sa.Column('distancia_km', sa.Float(), nullable=True),
    sa.Column('fecha_extraccion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asteroides_id'), 'asteroides', ['id'], unique=False)
    op.create_index(op.f('ix_asteroides_nasa_id'), 'asteroides', ['nasa_id'], unique=False)
    op.create_table('metricas_etl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registros_insertados', sa.Integer(), nullable=True),
    sa.Column('errores', sa.Integer(), nullable=True),
    sa.Column('tiempo_ejecucion', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricas_etl_id'), 'metricas_etl', ['id'], unique=False)
    op.create_table('neows_registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nasa_id', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('magnitud_absoluta', sa.Float(), nullable=True),
    sa.Column('diametro_min_km', sa.Float(), nullable=True),
    sa.Column('diametro_max_km', sa.Float(), nullable=True),
    sa.Column('es_peligroso', sa.Boolean(), nullable=True),
    sa.Column('fecha_aproximacion', sa.Date(), nullable=True),
    sa.Column('velocidad_km_s', sa.Float(), nullable=True),
    sa.Column('distancia_km', sa.Float(), nullable=True),
    sa.Column('fecha_extraccion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neows_registros_id'), 'neows_registros', ['id'], unique=False)
    op.create_index(op.f('ix_neows_registros_nasa_id'), 'neows_registros', ['nasa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_neows_registros_nasa_id'), table_name='neows_registros')
    op.drop_index(op.f('ix_neows_registros_id'), table_name='neows_registros')
    op.drop_table('neows_registros')
    op.drop_index(op.f('ix_metricas_etl_id'), table_name='metricas_etl')
    op.drop_table('metricas_etl')
    op.drop_index(op.f('ix_asteroides_nasa_id'), table_name='asteroides')
    op.drop_index(op.f('ix_asteroides_id'), table_name='asteroides')
    op.drop_table('asteroides')
    # ### end Alembic commands ###
